const items=[...LESSON_5,...LESSON_6,...LESSON_7];const grid=document.querySelector('#grid');
function cardHTML(x){return `<section class="card" data-lesson="${x.lesson}" data-track="${x.track}"><div class="cardhead"><div><span class="lessonpill">Lesson ${x.lesson}</span><b>${x.title}</b><small>${x.track}</small></div><span class="status">미채점</span></div><audio preload="metadata"></audio><div class="controls"><button class="play">▶ 재생</button><button class="rew">↶ 5초</button><button class="speed" data-speed="0.8">0.8×</button><button class="speed active" data-speed="1">1.0×</button><button class="speed" data-speed="1.2">1.2×</button><span class="time">0:00</span></div><div class="script">${x.script}</div><div class="actions"><button class="check">채점</button><button class="reset">다시</button><button class="reveal">정답 보기</button></div></section>`}grid.innerHTML=items.map(cardHTML).join('');
const cards=[...document.querySelectorAll('.card')],audioByTrack=new Map(cards.map(c=>[c.dataset.track,c.querySelector('audio')])),loadedTracks=new Set(),objectUrls=[];
function trackFromName(name){const base=name.split('/').pop();let m=base.match(/^L([567])-LT([12])-([ABC])\.mp3$/i);if(m)return `L${m[1]}-LT${m[2]}-${m[3].toUpperCase()}`;m=base.match(/^L0?([567])_Listen&Talk\s*([12])_([ABC])(?:_2)?\.mp3$/i);return m?`L${m[1]}-LT${m[2]}-${m[3].toUpperCase()}`:null}
function updateAudioStatus(msg){document.querySelector('#audioStatus').textContent=msg||`음원 ${loadedTracks.size} / 18${loadedTracks.size===18?' · 준비 완료 ✓':''}`}
function setTrackAudio(track,blob){if(!audioByTrack.has(track)||loadedTracks.has(track))return;const url=URL.createObjectURL(blob);objectUrls.push(url);audioByTrack.get(track).src=url;loadedTracks.add(track);updateAudioStatus()}
async function readZip(blob){const zip=await JSZip.loadAsync(blob);for(const e of Object.values(zip.files)){if(e.dir)continue;if(/\.zip$/i.test(e.name)){await readZip(await e.async('blob'));continue}if(!/\.mp3$/i.test(e.name))continue;const t=trackFromName(e.name);if(t)setTrackAudio(t,await e.async('blob'))}}
document.querySelector('#audioPicker').addEventListener('change',async e=>{const files=[...e.target.files];if(!files.length)return;updateAudioStatus('음원 읽는 중…');try{for(const f of files){if(/\.zip$/i.test(f.name))await readZip(f);else{const t=trackFromName(f.name);if(t)setTrackAudio(t,f)}}updateAudioStatus();if(!loadedTracks.size)alert('수행 범위 음원을 찾지 못했어. Lesson 5·6·7 교과서 MP3 ZIP을 선택해 줘.')}catch(err){console.error(err);updateAudioStatus('음원 읽기 실패');alert('ZIP을 읽는 중 오류가 났어. 다른 ZIP 또는 MP3 파일을 선택해 줘.')}});window.addEventListener('beforeunload',()=>objectUrls.forEach(URL.revokeObjectURL));
function normalize(s){return s.toLowerCase().replace(/[’']/g,"'").replace(/[^a-z0-9']+/g,' ').trim()}function updateScore(){const done=cards.filter(c=>c.dataset.done==='1').length;document.querySelector('#score').textContent=`${done} / 18`;localStorage.setItem('eng-listening-done',JSON.stringify(cards.filter(c=>c.dataset.done==='1').map(c=>c.dataset.track)))}
const saved=new Set(JSON.parse(localStorage.getItem('eng-listening-done')||'[]'));cards.forEach(c=>{if(saved.has(c.dataset.track)){c.dataset.done='1';c.querySelector('.status').textContent='완료'}});updateScore();
cards.forEach(card=>{const audio=card.querySelector('audio'),play=card.querySelector('.play');play.onclick=()=>{if(!audio.src){alert('먼저 위의 “MP3/ZIP 선택”에서 교과서 음원을 불러와 줘.');return}if(audio.paused){document.querySelectorAll('audio').forEach(a=>{if(a!==audio)a.pause()});audio.play();play.textContent='❚❚ 일시정지'}else{audio.pause();play.textContent='▶ 재생'}};audio.onpause=()=>play.textContent='▶ 재생';audio.onended=()=>play.textContent='▶ 재생';card.querySelector('.rew').onclick=()=>audio.currentTime=Math.max(0,audio.currentTime-5);card.querySelectorAll('.speed').forEach(b=>b.onclick=()=>{audio.playbackRate=+b.dataset.speed;card.querySelectorAll('.speed').forEach(x=>x.classList.toggle('active',x===b))});audio.ontimeupdate=()=>{const s=Math.floor(audio.currentTime),m=Math.floor(s/60),d=Math.floor(audio.duration||0);card.querySelector('.time').textContent=`${m}:${String(s%60).padStart(2,'0')} / ${Math.floor(d/60)}:${String(d%60).padStart(2,'0')}`};card.querySelector('.check').onclick=()=>{let ok=true;card.querySelectorAll('input.blank').forEach(i=>{const good=normalize(i.value)===normalize(i.dataset.answer);i.classList.toggle('correct',good);i.classList.toggle('wrong',!good);if(!good)ok=false});card.querySelector('.status').textContent=ok?'완료 ✓':'오답 있음';if(ok)card.dataset.done='1';updateScore()};card.querySelector('.reset').onclick=()=>{card.querySelectorAll('input.blank').forEach(i=>{i.value='';i.classList.remove('correct','wrong')});card.querySelector('.status').textContent='미채점';delete card.dataset.done;updateScore()};card.querySelector('.reveal').onclick=()=>{card.querySelectorAll('input.blank').forEach(i=>{i.value=i.dataset.answer;i.classList.remove('wrong');i.classList.add('correct')});card.querySelector('.status').textContent='정답 표시'}});
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.body.classList.remove('mock');document.querySelector('#mock').classList.remove('on');document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('on',x===b));const f=b.dataset.filter;cards.forEach(c=>c.classList.toggle('hide',f!=='all'&&c.dataset.lesson!==f))});document.querySelector('#mock').onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('on'));document.querySelector('#mock').classList.add('on');document.body.classList.add('mock');cards.forEach(c=>c.classList.remove('hide'));[...cards].sort(()=>Math.random()-.5).forEach(c=>grid.appendChild(c));window.scrollTo({top:0,behavior:'smooth'})};